#!/usr/bin/ruby

# This script is based on http://github.com/vitorgalvao/alfred-workflows (MarkdownBulletin) witch is licenced under The Unlicense licence (http://unlicense.org/UNLICENSE)

Encoding::default_external = Encoding::UTF_8 if defined? Encoding

# read text from shell
s = $stdin.read

# Non-standard manual indent (using non-breaking spaces)
s.gsub! /^\s{2}([^\s])/, '  \1'

# horizontal rule
s.gsub! /^\n(- *|\* *){3,}$/, "\n[rule]\n"

# bold and italic
s.gsub! /\*\*\*(\S.*?)\*\*\*/, '[b][i]\1[/i][/b]'
s.gsub! /___(\S.*?)___/, '[b][i]\1[/i][/b]'

# bold
s.gsub! /\*\*(\S.*?)\*\*/, '[b]\1[/b]'
s.gsub! /__(\S.*?)__/, '[b]\1[/b]'

# italic
s.gsub! /\*(\S.*?)\*/, '[i]\1[/i]'
s.gsub! /_(\S.*?)_/, '[i]\1[/i]'

# strike through
s.gsub! /~~(.*)~~/, '[s]\1[/s]'

# quote
s.gsub! /^>\s(.*)/, "[quote]\n\\1\n[/quote]"

# image that sends to url
#s.gsub! /\[!\[[^\]]*\]\(([^)]*)\)\]\(([^)]*)\)/, '[url=\2][img=\1][/url]'

# image
s.gsub! /!\[[^\]]*\]\(([^)]*)\)/, '[img]\1[/img]'

# url
s.gsub! /\[([^\]]*)\]\(([^)]*)\)/, '[url=\2]\1[/url]'

# code block
## with backticks
s.gsub! /^```([^\n]*)\n(.*?)```/m, '[spoiler=\1]\2[/spoiler]'
s.gsub! /\[\/spoiler\]\n\n/, "[/spoiler]\n"

## with spacing or tabs
s.gsub! /^(^ {4}|\t)/, "[code]\n\\1" # beginning
#s.gsub! /\A(^ {4}|\t)/, "[code]\n\\1" # if beginning of text
s.gsub! /^(( {4}|\t).*)\n/, "\\1\n[/code]\n" # end
#s.gsub! /^(( {4}|\t).*)$\z/, "\\1\n[/code]" # if end of text
s.gsub! /(^ {4}|\t)/, '' # middle

# inline code
s.gsub! /`(.*?)`/, '[highlight]\1[/highlight]'

# headers
tmp = "[b][size=6]\\1[/size][/b]\n"
s.gsub! /^#\s(.*?)[ #]*$/, tmp # big
s.gsub! /^(.*?)$\n^===[ =]*$/, tmp # big
tmp = "\n[b][size=5]\\1[/size][/b]"
s.gsub! /^##\s(.*?)[ #]*$/, tmp # medium
s.gsub! /^(.*?)$\n^---[ -]*$/, tmp # medium
s.gsub! /^###\s(.*?)[ #]*$/, "\n[b][size=4]\\1[/size][/b]" # small
s.gsub! /^####\s(.*?)[ #]*$/, "\n[b][size=2]\\1[/size][/b]" # very small

# lists
## unordered
s.gsub! /^([^-].*)\n^([*+-]\s)/, "\\1\n[list]\n\\2" # beginning
#s.gsub! /\A^([*+-]\s)/, "[list]\n\\1" # if beginning of text
s.gsub! /^([*+-]\s.*)\n(^[^-].*)/, "\\1\n[/list]\n\\2" # end
#s.gsub! /^([*+-]\s.*)\z/, "\\1\n[/list]" # if end of text
s.gsub! /^[*+-]\s(.*)/, '[*]\1[/*]' # middle
s.gsub! /\[\/list\]\n\n/, "[/list]\n"

## ordered
s.gsub! /^\n^(\d\.\s)/, "\n[list=1]\n\\1" # beginning
s.gsub! /\A^(\d\.\s)/, "[list=1]\n\\1" # if beginning of text
s.gsub! /^(\d\.\s.*)\n\n/, "\\1\n[/list]\n\n" # end
s.gsub! /^(\d\.\s.*)\z/, "\\1\n[/list]" # if end of text
s.gsub! /^\d\.\s(.*)/, '[*]\1[/*]' # middle

# footnotes
s.gsub! /^(\[\^.*?\].*)/, "\n\\1" # spacing between references
s.gsub! /^\n{2}(\[\^.*?\])/, "\n" + "—"*10 + "\n\\1" # division before references
s.gsub! /\[\^(.*?)\]/, '[sup]\1[/sup]' # footnotes in text

# new lines
#s.gsub! /^([a-zA-Z].*)\n^\s*([a-zA-Z])/, '\\1 \\2'
#s.gsub! /\n\n(\s*[^=\-#*+`])/, "\n\\1"
#s.gsub! /^(.*)\n\n(.*)$/, "\\1\n\\2"
s.gsub! /\n\n\n+/m, "\n\n"


### Non-standard ###

# youtube video links
s.gsub! /^(https?:\/\/www\.youtube\.com\/\S+)$/, "[center][youtube]\\1[/youtube][/center]"

# underline
s.gsub! /____(\S.*?)____/, '[u]\1[/u]'


print s
